stack: kdgm/newrelic-kontena
version: 0.1.0
description: Setup and configure NewRelic nrsysmond on kontena nodes.

variables:
  newrelic_license_key:
    type: string
    from:
      vault: NEWRELIC_LICENSE_KEY
      env: NEWRELIC_LICENSE
    to:
      vault: NEWRELIC_LICENSE_KEY

services:
  nrsysmond:
    build: .
    image: kdgm/newrelic-kontena:latest
    secrets:
      - secret: NEWRELIC_LICENSE_KEY
        name: NRSYSMOND_license_key
        type: env
    environment:
      NRSYSMOND_cgroup_style: 0
      # NRSYSMOND_host_root: /host
      # NRSYSMOND_cgroup_root: /host/sys/fs/cgroup
      # NRSYSMOND_loglevel: debug
    network_mode: host
    pid: host
    privileged: true
    deploy:
      strategy: daemon
    volumes:
      - /dev:/dev:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/run/docker.sock:/var/run/docker.sock
