stack: kdgm/newrelic
version: 0.1.0

variables:
  newrelic_license_key:
    type: string
    from:
      vault: NEWRELIC_LICENSE_KEY
      env: NEWRELIC_LICENSE
    to:
      vault: NEWRELIC_LICENSE_KEY

services:
  nrsysmond:
    build: .
    image: quay.io/kdgm/newrelic:latest
    secrets:
      - secret: NEWRELIC_LICENSE_KEY
        name: NRSYSMOND_license_key
        type: env
    environment:
      NRSYSMOND_cgroup_style: 0
      NRSYSMOND_host_root: /host
      NRSYSMOND_cgroup_root: /host/sys/fs/cgroup
      NRSYSMOND_loglevel: debug
    network_mode: host
    deploy:
      strategy: daemon
    volumes:
      - /proc:/host/proc:ro
      - /dev:/host/dev:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
      - /var/run/docker.sock:/var/run/docker.sock

# To run NewRelic system monitor (nrsysmond) on the master node
# run the following command:
#
# $ kontena master ssh -i kontena.pem \
#     docker run -d --restart always \
#       -e NRSYSMOND_hostname=kontena-master \
#       -e NRSYSMOND_license_key=NEWRELIC_LICENSE \
#       -e NRSYSMOND_cgroup_style=0 \
#       -e NRSYSMOND_host_root=/host \
#       -e NRSYSMOND_cgroup_root=/host/sys/fs/cgroup \
#       -e NRSYSMOND_loglevel=debug \
#       -v /proc:/host/proc:ro \
#       -v /dev:/host/dev:ro \
#       -v /sys/fs/cgroup:/host/sys/fs/cgroup:ro \
#       -v /var/run/docker.sock:/var/run/docker.sock \
#       christianbladescb/newrelic-coreos
