stack: kdgm/newrelic-kontena
version: 0.1.0
description: Setup and configure newrelic-infra agent on kontena nodes.

variables:
  newrelic_license_key:
    type: string
    from:
      vault: NEWRELIC_LICENSE_KEY
      env: NEWRELIC_LICENSE
    to:
      vault: NEWRELIC_LICENSE_KEY

services:
  newrelic-infra:
    build: .
    image: kdgm/newrelic-kontena:latest
    secrets:
      - secret: NEWRELIC_LICENSE_KEY
        name: NRIA_LICENSE_KEY
        type: env
    deploy:
      strategy: daemon
    network_mode: host
    volumes:
      - /:/host:ro
      - /var/run/docker.sock:/var/run/docker.sock
